# Copyright 2024 The HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Records a dataset. Actions for the robot can be either generated by teleoperation or by a policy.

Example:

```shell
lerobot-record \
    --robot.type=so100_follower \
    --robot.port=/dev/tty.usbmodem58760431541 \
    --robot.cameras="{laptop: {type: opencv, index_or_path: 0, width: 640, height: 480, fps: 30}}" \
    --robot.id=black \
    --dataset.repo_id=<my_username>/<my_dataset_name> \
    --dataset.num_episodes=2 \
    --dataset.single_task="Grab the cube" \
    --dataset.streaming_encoding=true \
    --dataset.encoder_threads=2 \
    --display_data=true
    # <- Optional: specify video codec (auto, h264, hevc, libsvtav1). Default is libsvtav1. \
    # --dataset.vcodec=h264 \
    # <- Teleop optional if you want to teleoperate to record or in between episodes with a policy \
    # --teleop.type=so100_leader \
    # --teleop.port=/dev/tty.usbmodem58760431551 \
    # --teleop.id=blue \
    # <- Policy optional if you want to record with a policy \
    # --policy.path=${HF_USER}/my_policy \
```

Example recording with bimanual so100:
```shell
lerobot-record \
  --robot.type=bi_so_follower \
  --robot.left_arm_config.port=/dev/tty.usbmodem5A460822851 \
  --robot.right_arm_config.port=/dev/tty.usbmodem5A460814411 \
  --robot.id=bimanual_follower \
  --robot.left_arm_config.cameras='{
    wrist: {"type": "opencv", "index_or_path": 1, "width": 640, "height": 480, "fps": 30},
    top: {"type": "opencv", "index_or_path": 3, "width": 640, "height": 480, "fps": 30},
  }' --robot.right_arm_config.cameras='{
    wrist: {"type": "opencv", "index_or_path": 2, "width": 640, "height": 480, "fps": 30},
    front: {"type": "opencv", "index_or_path": 4, "width": 640, "height": 480, "fps": 30},
  }' \
  --teleop.type=bi_so_leader \
  --teleop.left_arm_config.port=/dev/tty.usbmodem5A460852721 \
  --teleop.right_arm_config.port=/dev/tty.usbmodem5A460819811 \
  --teleop.id=bimanual_leader \
  --display_data=true \
  --dataset.repo_id=${HF_USER}/bimanual-so-handover-cube \
  --dataset.num_episodes=25 \
  --dataset.single_task="Grab and handover the red cube to the other arm" \
  --dataset.streaming_encoding=true \
  # --dataset.vcodec=auto \
  --dataset.encoder_threads=2
```
"""

import json
import logging
import sys
import time
import traceback
from contextlib import nullcontext
from dataclasses import asdict, dataclass, field
from pathlib import Path
from pprint import pformat
from typing import Any

from huggingface_hub import hf_hub_download
from huggingface_hub.constants import CONFIG_NAME

from lerobot.cameras import (  # noqa: F401
    CameraConfig,  # noqa: F401
)
from lerobot.cameras.opencv.configuration_opencv import OpenCVCameraConfig  # noqa: F401
from lerobot.cameras.reachy2_camera.configuration_reachy2_camera import Reachy2CameraConfig  # noqa: F401
from lerobot.cameras.realsense.configuration_realsense import RealSenseCameraConfig  # noqa: F401
from lerobot.cameras.zmq.configuration_zmq import ZMQCameraConfig  # noqa: F401
from lerobot.configs import parser
from lerobot.configs.policies import PreTrainedConfig
from lerobot.datasets.feature_utils import build_dataset_frame, combine_feature_dicts
from lerobot.datasets.image_writer import safe_stop_image_writer
from lerobot.datasets.lerobot_dataset import LeRobotDataset
from lerobot.datasets.pipeline_features import aggregate_pipeline_dataset_features, create_initial_features
from lerobot.datasets.video_utils import VideoEncodingManager
from lerobot.policies.factory import make_policy, make_pre_post_processors
from lerobot.policies.pretrained import PreTrainedPolicy
from lerobot.policies.utils import make_robot_action
from lerobot.processor import (
    PolicyAction,
    PolicyProcessorPipeline,
    RobotAction,
    RobotObservation,
    RobotProcessorPipeline,
    make_default_processors,
)
from lerobot.processor.rename_processor import rename_stats
from lerobot.robots import (  # noqa: F401
    Robot,
    RobotConfig,
    bi_openarm_follower,
    bi_so_follower,
    earthrover_mini_plus,
    hope_jr,
    koch_follower,
    make_robot_from_config,
    omx_follower,
    openarm_follower,
    reachy2,
    so_follower,
    unitree_g1 as unitree_g1_robot,
)
from lerobot.teleoperators import (  # noqa: F401
    Teleoperator,
    TeleoperatorConfig,
    bi_openarm_leader,
    bi_so_leader,
    homunculus,
    koch_leader,
    make_teleoperator_from_config,
    omx_leader,
    openarm_leader,
    openarm_mini,
    reachy2_teleoperator,
    so_leader,
    unitree_g1,
)
from lerobot.teleoperators.keyboard.teleop_keyboard import KeyboardTeleop
from lerobot.utils.constants import ACTION, OBS_STR, POLICY_POSTPROCESSOR_DEFAULT_NAME, POLICY_PREPROCESSOR_DEFAULT_NAME
from lerobot.utils.control_utils import (
    init_keyboard_listener,
    is_headless,
    predict_action,
    sanity_check_dataset_name,
    sanity_check_dataset_robot_compatibility,
)
from lerobot.utils.chrome_trace import ChromeTraceRecorder
from lerobot.utils.device_utils import get_safe_torch_device
from lerobot.utils.import_utils import register_third_party_plugins
from lerobot.utils.robot_utils import precise_sleep
from lerobot.utils.utils import (
    init_logging,
    log_say,
)
from lerobot.utils.visualization_utils import init_rerun, log_rerun_data


def _resolve_pretrained_artifact_paths(pretrained_path: str | Path) -> dict[str, Path]:
    pretrained_path = Path(pretrained_path) if isinstance(pretrained_path, Path) else Path(str(pretrained_path))
    if pretrained_path.is_dir():
        model_dir = pretrained_path.resolve()
        return {
            "model_dir": model_dir,
            "config": model_dir / CONFIG_NAME,
            "preprocessor": model_dir / f"{POLICY_PREPROCESSOR_DEFAULT_NAME}.json",
            "postprocessor": model_dir / f"{POLICY_POSTPROCESSOR_DEFAULT_NAME}.json",
        }

    repo_id = str(pretrained_path)
    config_path = Path(hf_hub_download(repo_id=repo_id, filename=CONFIG_NAME))
    preprocessor_path = Path(
        hf_hub_download(repo_id=repo_id, filename=f"{POLICY_PREPROCESSOR_DEFAULT_NAME}.json")
    )
    postprocessor_path = Path(
        hf_hub_download(repo_id=repo_id, filename=f"{POLICY_POSTPROCESSOR_DEFAULT_NAME}.json")
    )
    return {
        "model_dir": config_path.parent,
        "config": config_path,
        "preprocessor": preprocessor_path,
        "postprocessor": postprocessor_path,
    }


def safe_disconnect_devices(robot: Robot | None, teleop: Teleoperator | None) -> None:
    if robot is not None:
        try:
            if robot.is_connected:
                robot.disconnect()
        except Exception:
            logging.exception("Failed disconnecting robot during shutdown.")

    if teleop is not None:
        try:
            if teleop.is_connected:
                teleop.disconnect()
        except Exception:
            logging.exception("Failed disconnecting teleoperator during shutdown.")


RESET_STATE_KEYS = [*(f"joint{i}.pos" for i in range(1, 7)), "gripper.pos", "DO_0", "DO_1"]


def _validate_reset_state(saved_reset_state: dict[str, Any]) -> dict[str, float]:
    missing = [key for key in RESET_STATE_KEYS if key not in saved_reset_state]
    if missing:
        raise ValueError(f"Reset state is missing keys: {missing}")
    return {key: float(saved_reset_state[key]) for key in RESET_STATE_KEYS}


def _load_initial_pose(path: str | Path | None) -> dict[str, float] | None:
    if path is None:
        return None
    pose_path = Path(path)
    if not pose_path.exists():
        logging.info("Initial pose file does not exist yet: %s", pose_path)
        return None
    try:
        payload = json.loads(pose_path.read_text())
        state = _validate_reset_state(payload)
    except Exception as exc:
        logging.warning("Ignoring invalid initial pose file %s: %s", pose_path, exc)
        return None
    logging.info("Loaded initial pose from %s", pose_path)
    return state


def _save_initial_pose(path: str | Path | None, saved_reset_state: dict[str, float] | None) -> bool:
    if path is None or saved_reset_state is None:
        return False
    pose_path = Path(path)
    pose_path.parent.mkdir(parents=True, exist_ok=True)
    payload = _validate_reset_state(saved_reset_state)
    tmp_path = pose_path.with_suffix(f"{pose_path.suffix}.tmp")
    tmp_path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n")
    tmp_path.replace(pose_path)
    logging.info("Saved initial pose to %s", pose_path)
    return True


def _poll_teleop_control_events(teleop: Teleoperator | list[Teleoperator] | None, events: dict[str, bool]) -> None:
    teleops = teleop if isinstance(teleop, list) else [teleop]
    for teleop_device in teleops:
        if teleop_device is None or not hasattr(teleop_device, "consume_control_events"):
            continue
        pending = teleop_device.consume_control_events()
        for event_name in pending:
            if event_name in events:
                events[event_name] = True


def _capture_reset_state_from_observation(observation: RobotObservation) -> dict[str, float]:
    missing = [key for key in RESET_STATE_KEYS if key not in observation]
    if missing:
        raise ValueError(f"Cannot capture reset state, missing observation keys: {missing}")
    return _validate_reset_state({key: observation[key] for key in RESET_STATE_KEYS})


def _apply_saved_reset_state(
    robot: Robot,
    teleop: Teleoperator | list[Teleoperator] | None,
    saved_reset_state: dict[str, float] | None,
) -> bool:
    if saved_reset_state is None:
        return False
    joint_positions = [saved_reset_state[f"joint{i}.pos"] for i in range(1, 7)]
    teleops = teleop if isinstance(teleop, list) else [teleop]

    for teleop_device in teleops:
        if teleop_device is None or not hasattr(teleop_device, "move_to_joint_positions"):
            continue
        try:
            teleop_device.move_to_joint_positions(joint_positions)
            if hasattr(teleop_device, "apply_saved_control_state"):
                teleop_device.apply_saved_control_state(saved_reset_state)
            logging.info("Applied saved reset state to teleoperator %s.", type(teleop_device).__name__)
            return True
        except Exception:
            logging.exception("Failed applying saved reset state to teleoperator; trying robot fallback.")

    if not hasattr(robot, "move_to_joint_positions") or not hasattr(robot, "send_action"):
        logging.warning("Robot %s does not support saved reset state application; skipping.", robot.name)
        return False

    try:
        robot.move_to_joint_positions(joint_positions)
        robot.send_action(
            {
                "gripper.pos": saved_reset_state["gripper.pos"],
                "DO_0": saved_reset_state["DO_0"],
                "DO_1": saved_reset_state["DO_1"],
            }
        )
    except Exception:
        logging.exception("Failed applying saved reset state; continuing without interrupting recording.")
        return False
    return True


def _get_record_action_features(
    robot: Robot,
    teleop: Teleoperator | list[Teleoperator] | None,
    has_policy: bool,
) -> dict[str, Any]:
    # For teleop-only data collection, preserve the teleoperator's richer action schema
    # (for example Lebai leader tcp.* fields) in the dataset action. Policy-driven record/eval
    # keeps the robot control action schema so existing postprocessors and checkpoints still match.
    if not has_policy and isinstance(teleop, Teleoperator):
        return teleop.action_features
    return robot.action_features


def _apply_manual_end_effector_override(
    action: dict[str, Any] | PolicyAction,
    teleop: Teleoperator | list[Teleoperator] | None,
    action_feature_names: list[str] | None = None,
) -> dict[str, Any] | PolicyAction:
    teleops = teleop if isinstance(teleop, list) else [teleop]
    if isinstance(action, dict):
        overridden_action: dict[str, Any] | PolicyAction = dict(action)
        action_name_to_index = None
    else:
        overridden_action = action.clone()
        action_name_to_index = (
            {name: idx for idx, name in enumerate(action_feature_names)} if action_feature_names is not None else {}
        )

    for teleop_device in teleops:
        if teleop_device is None:
            continue

        if hasattr(teleop_device, "gripper_target"):
            gripper_target = float(getattr(teleop_device, "gripper_target"))
            if isinstance(overridden_action, dict):
                if "gripper.pos" in overridden_action:
                    overridden_action["gripper.pos"] = gripper_target
            elif "gripper.pos" in action_name_to_index:
                overridden_action[..., action_name_to_index["gripper.pos"]] = gripper_target

        if hasattr(teleop_device, "do0_target"):
            do0_target = float(getattr(teleop_device, "do0_target"))
            if isinstance(overridden_action, dict):
                if "DO_0" in overridden_action:
                    overridden_action["DO_0"] = do0_target
            elif "DO_0" in action_name_to_index:
                overridden_action[..., action_name_to_index["DO_0"]] = do0_target

        if hasattr(teleop_device, "do1_target"):
            do1_target = float(getattr(teleop_device, "do1_target"))
            if isinstance(overridden_action, dict):
                if "DO_1" in overridden_action:
                    overridden_action["DO_1"] = do1_target
            elif "DO_1" in action_name_to_index:
                overridden_action[..., action_name_to_index["DO_1"]] = do1_target

    return overridden_action


@dataclass
class DatasetRecordConfig:
    # Dataset identifier. By convention it should match '{hf_username}/{dataset_name}' (e.g. `lerobot/test`).
    repo_id: str
    # A short but accurate description of the task performed during the recording (e.g. "Pick the Lego block and drop it in the box on the right.")
    single_task: str
    # Root directory where the dataset will be stored (e.g. 'dataset/path'). If None, defaults to $HF_LEROBOT_HOME/repo_id.
    root: str | Path | None = None
    # Limit the frames per second.
    fps: int = 30
    # Number of seconds for data recording for each episode.
    episode_time_s: int | float = 60
    # Number of seconds for resetting the environment after each episode.
    reset_time_s: int | float = 60
    # Number of episodes to record.
    num_episodes: int = 50
    # Encode frames in the dataset into video
    video: bool = True
    # Upload dataset to Hugging Face hub.
    push_to_hub: bool = True
    # Upload on private repository on the Hugging Face hub.
    private: bool = False
    # Add tags to your dataset on the hub.
    tags: list[str] | None = None
    # Number of subprocesses handling the saving of frames as PNG. Set to 0 to use threads only;
    # set to ≥1 to use subprocesses, each using threads to write images. The best number of processes
    # and threads depends on your system. We recommend 4 threads per camera with 0 processes.
    # If fps is unstable, adjust the thread count. If still unstable, try using 1 or more subprocesses.
    num_image_writer_processes: int = 0
    # Number of threads writing the frames as png images on disk, per camera.
    # Too many threads might cause unstable teleoperation fps due to main thread being blocked.
    # Not enough threads might cause low camera fps.
    num_image_writer_threads_per_camera: int = 4
    # Number of episodes to record before batch encoding videos
    # Set to 1 for immediate encoding (default behavior), or higher for batched encoding
    video_encoding_batch_size: int = 1
    # Video codec for encoding videos. Options: 'h264', 'hevc', 'libsvtav1', 'auto',
    # or hardware-specific: 'h264_videotoolbox', 'h264_nvenc', 'h264_vaapi', 'h264_qsv'.
    # Use 'auto' to auto-detect the best available hardware encoder.
    vcodec: str = "libsvtav1"
    # Enable streaming video encoding: encode frames in real-time during capture instead
    # of writing PNG images first. Makes save_episode() near-instant. More info in the documentation: https://huggingface.co/docs/lerobot/streaming_video_encoding
    streaming_encoding: bool = False
    # Maximum number of frames to buffer per camera when using streaming encoding.
    # ~1s buffer at 30fps. Provides backpressure if the encoder can't keep up.
    encoder_queue_maxsize: int = 30
    # Number of threads per encoder instance. None = auto (codec default).
    # Lower values reduce CPU usage, maps to 'lp' (via svtav1-params) for libsvtav1 and 'threads' for h264/hevc..
    encoder_threads: int | None = None
    # Rename map for the observation to override the image and state keys
    rename_map: dict[str, str] = field(default_factory=dict)

    def __post_init__(self):
        if self.single_task is None:
            raise ValueError("You need to provide a task as argument in `single_task`.")


@dataclass
class RecordConfig:
    robot: RobotConfig
    dataset: DatasetRecordConfig
    # Whether to control the robot with a teleoperator
    teleop: TeleoperatorConfig | None = None
    # Whether to control the robot with a policy
    policy: PreTrainedConfig | None = None
    # Display all cameras on screen
    display_data: bool = False
    # Display data on a remote Rerun server
    display_ip: str | None = None
    # Port of the remote Rerun server
    display_port: int | None = None
    # Whether to  display compressed images in Rerun
    display_compressed_images: bool = False
    # Use vocal synthesis to read events.
    play_sounds: bool = True
    # Resume recording on an existing dataset.
    resume: bool = False
    # Optional JSON file used to persist/reset a shared initial pose across sessions.
    initial_pose_path: str | Path | None = None
    # Whether save events should immediately overwrite the initial pose JSON when configured.
    autosave_initial_pose: bool = True
    # Optional chrome trace json output for profiling the record loop.
    trace_path: str | Path | None = None
    # If True, teleop/gamepad gripper and DO targets override the policy end-effector outputs during inference.
    teleop_end_effector_override: bool = False

    def __post_init__(self):
        # HACK: We parse again the cli args here to get the pretrained path if there was one.
        policy_path = parser.get_path_arg("policy")

        if policy_path:
            cli_overrides = parser.get_cli_overrides("policy")

            self.policy = PreTrainedConfig.from_pretrained(policy_path, cli_overrides=cli_overrides)
            self.policy.pretrained_path = policy_path

        if self.teleop is None and self.policy is None:
            raise ValueError("Choose a policy, a teleoperator or both to control the robot")

    @classmethod
    def __get_path_fields__(cls) -> list[str]:
        """This enables the parser to load config from the policy using `--policy.path=local/dir`"""
        return ["policy"]


""" --------------- record_loop() data flow --------------------------
       [ Robot ]
           V
     [ robot.get_observation() ] ---> raw_obs
           V
     [ robot_observation_processor ] ---> processed_obs
           V
     .-----( ACTION LOGIC )------------------.
     V                                       V
     [ From Teleoperator ]                   [ From Policy ]
     |                                       |
     |  [teleop.get_action] -> raw_action    |   [predict_action]
     |          |                            |          |
     |          V                            |          V
     | [teleop_action_processor]             |          |
     |          |                            |          |
     '---> processed_teleop_action           '---> processed_policy_action
     |                                       |
     '-------------------------.-------------'
                               V
                  [ robot_action_processor ] --> robot_action_to_send
                               V
                    [ robot.send_action() ] -- (Robot Executes)
                               V
                    ( Save to Dataset )
                               V
                  ( Rerun Log / Loop Wait )
"""


@safe_stop_image_writer
def record_loop(
    robot: Robot,
    events: dict,
    fps: int,
    teleop_action_processor: RobotProcessorPipeline[
        tuple[RobotAction, RobotObservation], RobotAction
    ],  # runs after teleop
    robot_action_processor: RobotProcessorPipeline[
        tuple[RobotAction, RobotObservation], RobotAction
    ],  # runs before robot
    robot_observation_processor: RobotProcessorPipeline[
        RobotObservation, RobotObservation
    ],  # runs after robot
    dataset: LeRobotDataset | None = None,
    teleop: Teleoperator | list[Teleoperator] | None = None,
    policy: PreTrainedPolicy | None = None,
    preprocessor: PolicyProcessorPipeline[dict[str, Any], dict[str, Any]] | None = None,
    postprocessor: PolicyProcessorPipeline[PolicyAction, PolicyAction] | None = None,
    teleop_end_effector_override: bool = False,
    control_time_s: int | None = None,
    single_task: str | None = None,
    phase_name: str = "recording",
    display_data: bool = False,
    display_compressed_images: bool = False,
    saved_reset_state_ref: dict[str, dict[str, float] | None] | None = None,
    initial_pose_path: str | Path | None = None,
    autosave_initial_pose: bool = True,
    trace_recorder: ChromeTraceRecorder | None = None,
):
    if dataset is not None and dataset.fps != fps:
        raise ValueError(f"The dataset fps should be equal to requested fps ({dataset.fps} != {fps}).")

    teleop_arm = teleop_keyboard = None
    if isinstance(teleop, list):
        teleop_keyboard = next((t for t in teleop if isinstance(t, KeyboardTeleop)), None)
        teleop_arm = next(
            (
                t
                for t in teleop
                if isinstance(
                    t,
                    (
                        so_leader.SO100Leader
                        | so_leader.SO101Leader
                        | koch_leader.KochLeader
                        | omx_leader.OmxLeader
                    ),
                )
            ),
            None,
        )

        if not (teleop_arm and teleop_keyboard and len(teleop) == 2 and robot.name == "lekiwi_client"):
            raise ValueError(
                "For multi-teleop, the list must contain exactly one KeyboardTeleop and one arm teleoperator. Currently only supported for LeKiwi robot."
            )

    # Reset policy and processor if they are provided
    if policy is not None and preprocessor is not None and postprocessor is not None:
        policy.reset()
        preprocessor.reset()
        postprocessor.reset()

    no_action_count = 0
    timestamp = 0
    start_episode_t = time.perf_counter()
    duration_s = float(control_time_s) if control_time_s is not None else float("nan")
    banner = "=" * 72

    def trace_span(name: str, args: dict[str, Any] | None = None):
        if trace_recorder is None or not trace_recorder.enabled:
            return nullcontext()
        return trace_recorder.span(name, args=args, category="record")

    def emit_phase_banner() -> None:
        sys.stdout.write(
            f"\n{banner}\n"
            f"PHASE: {phase_name.upper()}\n"
            f"DURATION: {duration_s:.1f}s\n"
            f"{banner}\n"
        )
        sys.stdout.flush()

    recording_banner_delay_s = 2.0
    banner_printed = not phase_name.lower().startswith("recording")
    if banner_printed:
        emit_phase_banner()

    while timestamp < control_time_s:
        start_loop_t = time.perf_counter()

        with trace_span("loop.poll_events"):
            _poll_teleop_control_events(teleop, events)

        if events["exit_early"]:
            events["exit_early"] = False
            break

        # Get robot observation
        with trace_span("loop.get_observation"):
            obs = robot.get_observation()
        if saved_reset_state_ref is not None:
            if events.get("save_reset_state", False):
                saved_reset_state_ref["value"] = _capture_reset_state_from_observation(obs)
                events["save_reset_state"] = False
                logging.info("Saved reset state from current follower observation.")
                if autosave_initial_pose:
                    _save_initial_pose(initial_pose_path, saved_reset_state_ref["value"])
            if events.get("clear_reset_state", False):
                saved_reset_state_ref["value"] = None
                events["clear_reset_state"] = False
                logging.info("Cleared saved reset state.")
            if events.get("load_reset_state", False):
                events["load_reset_state"] = False
                loaded_reset_state = _load_initial_pose(initial_pose_path)
                if loaded_reset_state is not None:
                    saved_reset_state_ref["value"] = loaded_reset_state
                if saved_reset_state_ref["value"] is None:
                    logging.info("No saved reset state available to apply.")
                else:
                    _apply_saved_reset_state(robot, teleop, saved_reset_state_ref["value"])
                    continue

        # Applies a pipeline to the raw robot observation, default is IdentityProcessor
        with trace_span("loop.process_observation"):
            obs_processed = robot_observation_processor(obs)

        if policy is not None or dataset is not None:
            with trace_span("loop.build_observation_frame"):
                observation_frame = build_dataset_frame(dataset.features, obs_processed, prefix=OBS_STR)

        # Get action from either policy or teleop
        if policy is not None and preprocessor is not None and postprocessor is not None:
            with trace_span("loop.predict_action"):
                action_values = predict_action(
                    observation=observation_frame,
                    policy=policy,
                    device=get_safe_torch_device(policy.config.device),
                    preprocessor=preprocessor,
                    postprocessor=postprocessor,
                    use_amp=policy.config.use_amp,
                    task=single_task,
                    robot_type=robot.robot_type,
                )

            if teleop_end_effector_override:
                with trace_span("loop.manual_ee_override"):
                    action_values = _apply_manual_end_effector_override(
                        action_values,
                        teleop,
                        action_feature_names=dataset.features[ACTION]["names"] if dataset is not None else None,
                    )

            with trace_span("loop.make_robot_action"):
                act_processed_policy = make_robot_action(action_values, dataset.features)

        elif policy is None and isinstance(teleop, Teleoperator):
            if robot.name == "unitree_g1":
                with trace_span("loop.teleop_feedback"):
                    teleop.send_feedback(obs)
            with trace_span("loop.teleop_get_action"):
                act = teleop.get_action()

            # Applies a pipeline to the raw teleop action, default is IdentityProcessor
            with trace_span("loop.process_teleop_action"):
                act_processed_teleop = teleop_action_processor((act, obs))

        elif policy is None and isinstance(teleop, list):
            with trace_span("loop.teleop_arm_get_action"):
                arm_action = teleop_arm.get_action()
            arm_action = {f"arm_{k}": v for k, v in arm_action.items()}
            with trace_span("loop.teleop_keyboard_get_action"):
                keyboard_action = teleop_keyboard.get_action()
            with trace_span("loop.keyboard_to_base_action"):
                base_action = robot._from_keyboard_to_base_action(keyboard_action)
            act = {**arm_action, **base_action} if len(base_action) > 0 else arm_action
            with trace_span("loop.process_teleop_action"):
                act_processed_teleop = teleop_action_processor((act, obs))
        else:
            no_action_count += 1
            if no_action_count == 1 or no_action_count % 10 == 0:
                logging.warning(
                    f"[{phase_name}] No policy or teleoperator provided, skipping action generation. "
                    "This is likely to happen when resetting the environment without a teleop device. "
                    "The robot won't be at its rest position at the start of the next episode."
                )
            continue

        # Applies a pipeline to the action, default is IdentityProcessor
        if policy is not None and act_processed_policy is not None:
            action_values = act_processed_policy
            with trace_span("loop.process_robot_action"):
                robot_action_to_send = robot_action_processor((act_processed_policy, obs))
        else:
            action_values = act_processed_teleop
            with trace_span("loop.process_robot_action"):
                robot_action_to_send = robot_action_processor((act_processed_teleop, obs))

        # Send action to robot
        # Action can eventually be clipped using `max_relative_target`,
        # so action actually sent is saved in the dataset. action = postprocessor.process(action)
        # TODO(steven, pepijn, adil): we should use a pipeline step to clip the action, so the sent action is the action that we input to the robot.
        with trace_span("loop.send_action"):
            _sent_action = robot.send_action(robot_action_to_send)

        # Write to dataset
        if dataset is not None:
            with trace_span("loop.build_action_frame"):
                action_frame = build_dataset_frame(dataset.features, action_values, prefix=ACTION)
            frame = {**observation_frame, **action_frame, "task": single_task}
            with trace_span("loop.dataset_add_frame"):
                dataset.add_frame(frame)

        if display_data:
            with trace_span("loop.display"):
                log_rerun_data(
                    observation=obs_processed, action=action_values, compress_images=display_compressed_images
                )

        dt_s = time.perf_counter() - start_loop_t

        sleep_time_s: float = 1 / fps - dt_s
        if sleep_time_s < 0:
                logging.warning(
                    f"[{phase_name}] Record loop is running slower ({1 / dt_s:.1f} Hz) than the target FPS ({fps} Hz). Dataset frames might be dropped and robot control might be unstable. Common causes are: 1) Camera FPS not keeping up 2) Policy inference taking too long 3) CPU starvation"
                )

        precise_sleep(max(sleep_time_s, 0.0))

        timestamp = time.perf_counter() - start_episode_t
        if not banner_printed and timestamp >= recording_banner_delay_s:
            emit_phase_banner()
            banner_printed = True


@parser.wrap()
def record(cfg: RecordConfig) -> LeRobotDataset:
    init_logging()
    logging.info(pformat(asdict(cfg)))
    if cfg.display_data:
        init_rerun(session_name="recording", ip=cfg.display_ip, port=cfg.display_port)
    display_compressed_images = (
        True
        if (cfg.display_data and cfg.display_ip is not None and cfg.display_port is not None)
        else cfg.display_compressed_images
    )

    robot = make_robot_from_config(cfg.robot)
    teleop = make_teleoperator_from_config(cfg.teleop) if cfg.teleop is not None else None

    teleop_action_processor, robot_action_processor, robot_observation_processor = make_default_processors()
    trace_recorder = ChromeTraceRecorder(cfg.trace_path, process_name="lerobot-record")
    trace_recorder.set_thread_name("record-main")

    record_action_features = _get_record_action_features(robot, teleop, has_policy=cfg.policy is not None)
    dataset_features = combine_feature_dicts(
        aggregate_pipeline_dataset_features(
            pipeline=teleop_action_processor,
            initial_features=create_initial_features(
                action=record_action_features
            ),  # TODO(steven, pepijn): in future this should be come from teleop or policy
            use_videos=cfg.dataset.video,
        ),
        aggregate_pipeline_dataset_features(
            pipeline=robot_observation_processor,
            initial_features=create_initial_features(observation=robot.observation_features),
            use_videos=cfg.dataset.video,
        ),
    )

    dataset = None
    listener = None
    exit_code = 0
    completed_successfully = False
    saved_reset_state_ref: dict[str, dict[str, float] | None] = {"value": _load_initial_pose(cfg.initial_pose_path)}

    try:
        if cfg.resume:
            dataset = LeRobotDataset(
                cfg.dataset.repo_id,
                root=cfg.dataset.root,
                batch_encoding_size=cfg.dataset.video_encoding_batch_size,
                vcodec=cfg.dataset.vcodec,
                streaming_encoding=cfg.dataset.streaming_encoding,
                encoder_queue_maxsize=cfg.dataset.encoder_queue_maxsize,
                encoder_threads=cfg.dataset.encoder_threads,
            )

            if hasattr(robot, "cameras") and len(robot.cameras) > 0:
                dataset.start_image_writer(
                    num_processes=cfg.dataset.num_image_writer_processes,
                    num_threads=cfg.dataset.num_image_writer_threads_per_camera * len(robot.cameras),
                )
            sanity_check_dataset_robot_compatibility(dataset, robot, cfg.dataset.fps, dataset_features)
        else:
            # Create empty dataset or load existing saved episodes
            sanity_check_dataset_name(cfg.dataset.repo_id, cfg.policy)
            dataset = LeRobotDataset.create(
                cfg.dataset.repo_id,
                cfg.dataset.fps,
                root=cfg.dataset.root,
                robot_type=robot.name,
                features=dataset_features,
                use_videos=cfg.dataset.video,
                image_writer_processes=cfg.dataset.num_image_writer_processes,
                image_writer_threads=cfg.dataset.num_image_writer_threads_per_camera * len(robot.cameras),
                batch_encoding_size=cfg.dataset.video_encoding_batch_size,
                vcodec=cfg.dataset.vcodec,
                streaming_encoding=cfg.dataset.streaming_encoding,
                encoder_queue_maxsize=cfg.dataset.encoder_queue_maxsize,
                encoder_threads=cfg.dataset.encoder_threads,
            )

        # Load pretrained policy
        preprocessor = None
        postprocessor = None
        policy = None
        if cfg.policy is not None:
            resolved_policy_paths = _resolve_pretrained_artifact_paths(cfg.policy.pretrained_path)
            logging.info("Policy requested path: %s", cfg.policy.pretrained_path)
            logging.info("Policy resolved local model dir: %s", resolved_policy_paths["model_dir"])
            logging.info("Policy resolved config: %s", resolved_policy_paths["config"])
            logging.info("Policy resolved preprocessor config: %s", resolved_policy_paths["preprocessor"])
            logging.info("Policy resolved postprocessor config: %s", resolved_policy_paths["postprocessor"])
            policy = make_policy(cfg.policy, ds_meta=dataset.meta)
            preprocessor, postprocessor = make_pre_post_processors(
                policy_cfg=cfg.policy,
                pretrained_path=cfg.policy.pretrained_path,
                dataset_stats=rename_stats(dataset.meta.stats, cfg.dataset.rename_map),
                preprocessor_overrides={
                    "device_processor": {"device": cfg.policy.device},
                    "rename_observations_processor": {"rename_map": cfg.dataset.rename_map},
                },
            )

        robot.connect()
        if teleop is not None:
            teleop.connect()

        listener, events = init_keyboard_listener()

        if not cfg.dataset.streaming_encoding:
            logging.info(
                "Streaming encoding is disabled. If you have capable hardware, consider enabling it for way faster episode saving. --dataset.streaming_encoding=true --dataset.encoder_threads=2 # --dataset.vcodec=auto. More info in the documentation: https://huggingface.co/docs/lerobot/streaming_video_encoding"
            )

        with VideoEncodingManager(dataset):
            recorded_episodes = 0
            if cfg.dataset.reset_time_s > 0 and not events["stop_recording"]:
                log_say("Initial reset period", cfg.play_sounds)
                record_loop(
                    robot=robot,
                    events=events,
                    fps=cfg.dataset.fps,
                    teleop_action_processor=teleop_action_processor,
                    robot_action_processor=robot_action_processor,
                    robot_observation_processor=robot_observation_processor,
                    teleop=teleop,
                    control_time_s=cfg.dataset.reset_time_s,
                    single_task=cfg.dataset.single_task,
                    phase_name=f"reset before episode {dataset.num_episodes}",
                    display_data=cfg.display_data,
                    saved_reset_state_ref=saved_reset_state_ref,
                    initial_pose_path=cfg.initial_pose_path,
                    autosave_initial_pose=cfg.autosave_initial_pose,
                    trace_recorder=trace_recorder,
                    teleop_end_effector_override=cfg.teleop_end_effector_override,
                )
            while recorded_episodes < cfg.dataset.num_episodes and not events["stop_recording"]:
                log_say(f"Recording episode {dataset.num_episodes}", cfg.play_sounds)
                record_loop(
                    robot=robot,
                    events=events,
                    fps=cfg.dataset.fps,
                    teleop_action_processor=teleop_action_processor,
                    robot_action_processor=robot_action_processor,
                    robot_observation_processor=robot_observation_processor,
                    teleop=teleop,
                    policy=policy,
                    preprocessor=preprocessor,
                    postprocessor=postprocessor,
                    dataset=dataset,
                    control_time_s=cfg.dataset.episode_time_s,
                    single_task=cfg.dataset.single_task,
                    phase_name=f"recording episode {dataset.num_episodes}",
                    display_data=cfg.display_data,
                    display_compressed_images=display_compressed_images,
                    saved_reset_state_ref=saved_reset_state_ref,
                    initial_pose_path=cfg.initial_pose_path,
                    autosave_initial_pose=cfg.autosave_initial_pose,
                    trace_recorder=trace_recorder,
                    teleop_end_effector_override=cfg.teleop_end_effector_override,
                )

                # Execute a few seconds without recording to give time to manually reset the environment
                # Skip reset for the last episode to be recorded
                if not events["stop_recording"] and (
                    (recorded_episodes < cfg.dataset.num_episodes - 1) or events["rerecord_episode"]
                ):
                    log_say("Reset the environment", cfg.play_sounds)

                    record_loop(
                        robot=robot,
                        events=events,
                        fps=cfg.dataset.fps,
                        teleop_action_processor=teleop_action_processor,
                        robot_action_processor=robot_action_processor,
                        robot_observation_processor=robot_observation_processor,
                        teleop=teleop,
                        control_time_s=cfg.dataset.reset_time_s,
                        single_task=cfg.dataset.single_task,
                        phase_name=f"reset before episode {dataset.num_episodes + 1}",
                        display_data=cfg.display_data,
                        saved_reset_state_ref=saved_reset_state_ref,
                        initial_pose_path=cfg.initial_pose_path,
                        autosave_initial_pose=cfg.autosave_initial_pose,
                        trace_recorder=trace_recorder,
                        teleop_end_effector_override=cfg.teleop_end_effector_override,
                    )

                if events["rerecord_episode"]:
                    log_say("Re-record episode", cfg.play_sounds)
                    events["rerecord_episode"] = False
                    events["exit_early"] = False
                    dataset.clear_episode_buffer()
                    continue

                if dataset.episode_buffer is None or dataset.episode_buffer["size"] == 0:
                    logging.warning(
                        "No frames were recorded for episode %s; dropping it like a re-recorded episode.",
                        dataset.num_episodes,
                    )
                    dataset.clear_episode_buffer()
                    events["rerecord_episode"] = False
                    events["exit_early"] = False
                    continue

                dataset.save_episode()
                recorded_episodes += 1
        completed_successfully = True
    except KeyboardInterrupt:
        pass
    except Exception as exc:
        exit_code = 1
        logging.exception("Recording stopped due to device/runtime error: %s", exc)
        logging.error("Full traceback:\n%s", traceback.format_exc())
    finally:
        log_say("Stop recording", cfg.play_sounds, blocking=True)

        if dataset:
            dataset.finalize()

        safe_disconnect_devices(robot, teleop)

        if not is_headless() and listener:
            listener.stop()

        trace_recorder.close()
        if completed_successfully and dataset and cfg.dataset.push_to_hub:
            dataset.push_to_hub(tags=cfg.dataset.tags, private=cfg.dataset.private)

        log_say("Exiting", cfg.play_sounds)

    if exit_code:
        raise SystemExit(exit_code)
    return dataset


def main():
    register_third_party_plugins()
    record()


if __name__ == "__main__":
    main()
